function moduleAssignment = ERMMFit(C)
%-------------------------------------------------------------------------------
% Data from Fig. 2 of
% Pavlovic, D. M., Vértes, P. E., Bullmore, E., Schafer, W. R. & Nichols, T. E.
% Stochastic Blockmodeling of the Modules and Core of the Caenorhabditis elegans
% Connectome. PLoS ONE 9, e97584 (2014).
%-------------------------------------------------------------------------------
blocks = cell(9,1);
blocks{1} = {'ADFL','ADFR','AFDL','AFDR','AIAL','AIAR','AIMR','AINL','AINR','AIYL','AIYR',...
                'AIZL','AIZR','ASEL','ASER','ASGL','ASGR','ASIL','ASIR','ASJL','ASJR',...
                'ASKL','ASKR','AUAL','AUAR','AWAL','AWAR','AWBL','AWBR','AWCL','AWCR',...
                'BAGL','BAGR','BDUL','HSNL','PLNL','PLNR','RIR','SAADL','SMBVL','SMBVR'};
blocks{2} = {'ADAL','ADAR','ADEL','ADER','ADLL','ADLR','AIBL','AIBR','ALML','ASHL','ASHR',...
                'AVKL','AVKR','FLPL','RIAL','RIAR','RIBL','RIBR','RICL','RIGL','RIGR','RIH',...
                'RIML','RIMR','RIS','RMGL','RMGR','SAADR','SMBDL','SMBDR','URXL','URXR'};
blocks{3} = {'AS11','AS07','AS08','AS09','DA07','DA08','DA09','DB05','DB06','DB07',...
                'DD05','DD06','DVB','LUAL','LUAR','PDA','PDB','PDEL','PDER','PHAL','PHAR',...
                'PHBL','PHBR','PHCL','PHCR','PLML','PLMR','PQR','PVDL','PVDR','PVM','PVWL','PVWR',...
                'VA10','VA11','VA12','VA08','VA09','VB10','VB11','VB08','VB09','VD10','VD11',...
                'VD12','VD13','VD08','VD09'};
blocks{4} = {'AS01','AS02','AS03','AS04','AS05','AS06','AS10','DA01','DA02','DA03','DA04','DA05',...
                'DA06','DB02','DB03','DB04','DD04','SABD','SABVL','SABVR','VA01','VA02','VA03',...
                'VA04','VA05','VA06','VA07','VB03','VB04','VB05','VB06','VB07','VC04','VD07'};
blocks{5} = {'AVDL','AVDR','AVEL','AVER','DVA','PVR'};
blocks{6} = {'AVAL','AVAR','AVBL','AVBR','PVCL','PVCR'};
blocks{7} = {'AIML','AQR','AVFL','AVFR','AVG','AVHL','AVHR','AVJL','AVJR','AVL','AVM','BDUR',...
                'DVC','FLPR','HSNR','PVNL','PVNR','PVPL','PVPR','PVQL','PVQR','PVT','RID',...
                'RIFL','RIFR','VC05'};
blocks{8} = {'ALA','ALMR','ALNL','ALNR','CEPDL','CEPDR','CEPVL','CEPVR','IL1DL','IL1DR','IL1L','IL1R',...
            'IL1VL','IL1VR','IL2DL','IL2DR','IL2L','IL2R','IL2VL','IL2VR','OLLL','OLLR','OLQDL',...
            'OLQDR','OLQVL','OLQVR','RICR','RIPL','RIPR','RIVL','RIVR','RMDDL','RMDDR',...
            'RMDL','RMDR','RMDVL','RMDVR','RMED','RMEL','RMER','RMEV','RMFL','RMFR','RMHL','RMHR',...
            'SAAVL','SAAVR','SDQL','SDQR','SIADL','SIADR','SIAVL','SIAVR','SIBDL','SIBDR',...
            'SIBVL','SIBVR','SMDDL','SMDDR','SMDVL','SMDVR','URADL','URADR','URAVL','URAVR',...
            'URBL','URBR','URYDL','URYDR','URYVL','URYVR'};
blocks{9} = {'DB01','DD01','DD02','DD03','VB01','VB02','VC01','VC02','VC03','VD01','VD02',...
            'VD03','VD04','VD05','VD06'};


%-------------------------------------------------------------------------------
% Assign modules:
%-------------------------------------------------------------------------------
moduleAssignment = zeros(C.numNeurons,1);
for i = 1:C.numNeurons
    moduleAssignment(i) = find(cellfun(@(x)ismember(C.NeuronNames{i},x),blocks));
end

end
